apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ethereum-dev
  namespace: flux-system
spec:
  interval: 5m0s
  dependsOn:
    - name: infrastructure
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./overlays/development
  prune: true
  wait: true
  timeout: 10m