apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata: 
  name: ethereum-node
  namespace: ethereum
spec: 
  interval: 10m
  timeout: 30m

  chart:
    spec:
      chart: charts/ethereum-node
      sourceRef:
        kind: GitRepository
        name: ethereum-charts
        namespace: flux-system
      interval: 5m
  
  upgrade: 
    remediation:
      retries: 3
  
  rollback:
    recreate: true
    cleanupOnFail: true

  values:
    network: mainnet

    executionLayer:
      enabled: true
      replicas: 1
      image:
        repository: ethereum/client-go
        tag: v1.16.7
      resources:
        requests:
          memory: "8Gi"
          cpu: "2000m"
        limits:
          memory: "16Gi"
          cpu: "4000m"
        storage:
          size: 1Ti
          storageClass: fast-ssd
    
    consensusLayer:
      enabled: true
      replicas: 1
      image:
        repository: sigp/lighthouse
        tag: v4.5.0
      resources:
        requests:
          memory: "4Gi"
          cpu: "1000m"
        limits:
          memory: "8Gi"
          cpu: "2000m"
      storage:
        size: 200Gi
        storageClass: fast-ssd

    validator:
      enabled: false

    monitoring:
      enabled: true